# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 1234
  host: localhost
  port: 5432

development:
  <<: *default
  # ชื่อ Database
  database: auth_api_development

test:
  <<: *default
  database: auth_api_test

production:
  <<: *default
  database: auth_api_production
  username: <%= ENV['AUTH_API_DATABASE_USER'] %>
  password: <%= ENV['AUTH_API_DATABASE_PASSWORD'] %>